import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import { CartProvider } from '@/context/cart-context';
import { ToastProvider } from '@/context/toast-context';
import { AuthProvider } from '@/context/auth-context';
import Footer from '@/components/footer';
import { Navigation } from "@/components/nav_bar";
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pt-16">{/* give space for fixed navbar */}
          <ToastProvider>
            <AuthProvider>
              <CartProvider>
                <Navigation />
                {children}
                <Footer />
              </CartProvider>
            </AuthProvider>
          </ToastProvider>
           <Toaster richColors/>
        </div>
      </body>
    </html>
  );
}
